### ISSUE TITLE
Crashes with "Output in out.asm" enabled

### ISSUE THREAD

**Issue by arefdsg** [TriteHexagon/Midi2ASM-Converter#3]
tried the same file with it enabled and disabled, only worked with it disabled

**Comment by TriteHexagon** [comment]
It works fine for me; can you send me the midi file and all other configurations you used?

**Comment by arefdsg** [comment]
> Sent: Saturday, December 12, 2020 at 11:32 AM
> From: "TriteHexagon" <notifications@github.com>
> To: "TriteHexagon/Midi2ASM-Converter" <Midi2ASM-Converter@noreply.github.com>
> Cc: "arefdsg" <memedog@gmx.com>, "Author" <author@noreply.github.com>
> Subject: Re: [TriteHexagon/Midi2ASM-Converter] Crashes with "Output in out.asm" enabled (#3)
>
> It works fine for me; can you send me the midi file and all other configurations you used?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/TriteHexagon/Midi2ASM-Converter/issues/3#issuecomment-743736310
Default config with any midi, no idea what about it was doing it

**Comment by TriteHexagon** [comment]
Well, I can't help you much if I can't recreate the problem. I admit the program is a bit unstable, so sorry about the inconvenience.
